### ISSUE TITLE
`AnimatedTexture` improvements

### ISSUE THREAD

**Issue by oddbookworm** [durkisneer1/Kraken-Engine#24]
[might fail dramatically if the width and height of the spritesheet aren't **exactly** multiples of `width` and `height`](https://github.com/durkisneer1/Kraken-Engine/blob/0.0.2dev/src/AnimatedTexture.cpp#L62-L68)
  - Suggest failing out when that's the case
 
 [oops lol](https://github.com/durkisneer1/Kraken-Engine/blob/0.0.2dev/include/AnimatedTexture.hpp#L88)
  - Solution is obvious

`AnimatedTexture.cpp` -> `animated_texture.cpp` for consistency
  - Suggested alternative: Make implementation case match header case. As-is, my linter hates it because the names don't match and it doesn't link between header and implementation

[Overload for taking just the x and y, and then drawing the whole thing?](https://github.com/durkisneer1/Kraken-Engine/blob/0.0.2dev/include/AnimatedTexture.hpp#L71-L76)
  - Additional suggestion: use an enumeration as another arg to specify what part of the sprite is at that location. i.e. `TEXTURE_CENTER` could mean that `(x, y)` is the center of the sprite

Unit tests of course
  - I have a branch in work to fix the current unit tests in the first place

[explicitly put `void` as the argument of functions that don't take an argument](https://github.com/durkisneer1/Kraken-Engine/blob/0.0.2dev/include/AnimatedTexture.hpp#L52-L62)
  - Not required, but the behavior is technically different, and it might let the compiler do some more optimizations

[Inconsistent use of `Milliseconds` and `_ms`](https://github.com/durkisneer1/Kraken-Engine/blob/0.0.2dev/include/AnimatedTexture.hpp#L84-L86)
  - Make it be consistent of course lol

**Comment by oddbookworm** [comment]
Feel free to assign me to this @durkisneer1. Also, feel free to argue with any of these if you can make a good argument lol

**Comment by durkisneer1** [comment]
All good points. I'll take em into consideration and apply in code. 
![64634bf644ea290c3bbf033f_86](https://github.com/user-attachments/assets/e21e6135-17f8-4eee-b553-051e1028ca26)
